#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import (absolute_import, division,
                        print_function, unicode_literals)
from upho.phonon.sf_fitter import SFFitter

__author__ = 'Yuji Ikeda'


def main():
    import argparse
    parser = argparse.ArgumentParser()
    # parser.add_argument("-f", "--filenames",
    #                     nargs="+",
    #                     type=str,
    #                     required=True,
    #                     help="filenames for fitting")
    # parser.add_argument("--mode_band",
    #                     action="store_true",
    #                     help="Fitting for each band")
    parser.add_argument('--function',
                        type=str,
                        default='gaussian',
                        choices=['gaussian', 'lorentzian'],
                        help="Fitting function")
    args = parser.parse_args()

    SFFitter(name=args.function)


if __name__ == "__main__":
    main()
